language: python
python:
  - "3.8"
install:
  - pip install pipenv
  - pipenv sync --dev
script:
  - pipenv run bc fmt
  - pipenv run prospector
  - pipenv run pytest -m"not integration"
after_success:
  - coveralls